apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: qualified-cow-python 
  janus-idp.io/tekton: qualified-cow-python
  backstage.io/kubernetes-id: qualified-cow-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qualified-cow-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  