apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: qualified-cow-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qualified-cow-python 
  name: qualified-cow-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: qualified-cow-python 
